(function(_ds){var window=this;'use strict';var qR=function(){var a=_ds.N.call(this)||this;a.m=new _ds.yl;a.D=new _ds.yl;a.j=new Set;a.h=null;"IntersectionObserver"in window&&(a.h=new IntersectionObserver(function(b){b=_ds.p(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.lF(new _ds.jF,c),a.j.delete(c),a.h.unobserve(c))},{rootMargin:"100%"}));return a},rR=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.ni(c,b);c.appendChild(b)}})},zR=function(a,b){var c,d,e,f,h,k,l;return _ds.Va(function(m){if(1==m.j)return _ds.x(m,DevsiteApp.whenReady(),2);c=_ds.Wj();d=DevsiteApp.getInsecureHost();e=b.ra;if(e.origin!==c.origin&&d&&e.origin!==d)return m.return();try{f=_ds.Qg(_ds.rm,e.data)}catch(n){return m.return()}h=f.V(1,
0);if(4===h)return sR(a,e),m.return();k=f.getName();if(!k)return m.return();if(l=a.querySelector('devsite-iframe iframe[name="'+k+'"]'))switch(h){case 5:tR(f,l);break;case 8:uR(e,f,c);break;case 1:vR(e,f,c);break;case 6:case 7:wR(h,c,f);break;case 9:xR(a,f);break;case 10:yR(f,c)}_ds.y(m)})},tR=function(a,b){var c,d,e,f;_ds.Va(function(h){c=_ds.di(document).y;d=_ds.vg(a,4);e=_ds.vg(a,3);f=_ds.yi(b);d&&f.setAttribute("width",d+"px");e&&f.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.di(document).x,
c)});_ds.y(h)})},sR=function(a,b){var c,d,e;_ds.Va(function(f){if(c=AR(a,b.source)){d="goog_"+_ds.Dm++;c.setAttribute("name",d);var h=_ds.sm(3);e=_ds.Gg(h,2,d);(h=b.source)&&h.postMessage(_ds.Pg(e),"*")}_ds.y(f)})},uR=function(a,b,c){var d;_ds.Va(function(e){var f=_ds.tm(_ds.sm(8),_ds.J(b,8));d=_ds.Gg(f,6,c.toString());(f=a.source)&&f.postMessage(_ds.Pg(d),"*");_ds.y(e)})},vR=function(a,b,c){var d;_ds.Va(function(e){var f=_ds.tm(_ds.sm(2),_ds.J(b,8));d=_ds.Gg(f,7,c.search+c.hash);(f=a.source)&&f.postMessage(_ds.Pg(d),
"*");_ds.y(e)})},wR=function(a,b,c){var d,e,f;_ds.Va(function(h){d=c.getTitle();e=new URL(c.getUrl(),b.origin);f=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,f):window.history.replaceState({},d,f);_ds.y(h)})},xR=function(a,b){var c,d,e,f;_ds.Va(function(h){c=_ds.J(b,9);d=JSON.parse(_ds.J(b,10));"cloudtrackEvent"===c&&d?(e=d,f={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:f,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.y(h)})},yR=function(a,b){var c,d;_ds.Va(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.y(e)})},AR=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.Ci(d)===b&&(c=d)});return c},DR=function(a){a.C=a.querySelector(".devsite-article-body");
a.C&&BR(a);a.h&&a.h.disconnect();a.j.clear();rR(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, td > code, th > code"));a.j.clear();a.j=new Set(b);if(_ds.Wj().hash){b=new _ds.jF;for(var c=_ds.p(a.j),d=c.next();!d.done;d=c.next())_ds.lF(b,d.value)}else CR(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},BR=function(a){"full"===document.body.getAttribute("layout")&&(a=a.C.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},CR=function(a,b){a.h&&b.forEach(function(c){a.h.observe(c)})};_ds.r(qR,_ds.N);qR.prototype.connectedCallback=function(){var a=this;this.m.listen(window,"message",function(b){return zR(a,b)});DR(this)};qR.prototype.disconnectedCallback=function(){this.h&&this.h.disconnect();this.j.clear();_ds.El(this.m);_ds.El(this.D)};
qR.prototype.Xa=function(a){var b=this;a&&([".devsite-article","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.Fn(b,b.querySelector(c),a.querySelector(c))}),DR(this))};qR.prototype.updateContent=qR.prototype.Xa;qR.prototype.disconnectedCallback=qR.prototype.disconnectedCallback;qR.prototype.connectedCallback=qR.prototype.connectedCallback;try{window.customElements.define("devsite-content",qR)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
