(function(_ds){var window=this;'use strict';var T1=function(a,b){return _ds.ca[a]=b},U1=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return U1.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},V1=function(a,b,c,d,e,f,h,k,l,m){this.h=a;this.C=b;this.H=c;this.v=d;this.m=e;this.D=f;this.F=h;this.J=k;this.j=l;this.K=m},W1=function(a){return new V1(a.v,a.m,a.J,a.h,a.j,a.C,a.K,a.F,a.D,a.H)},X1=function(a,b){a.H=b;return a},Y1=function(a,b){a.D=b;return a},Z1=function(a,b){a.F=b;
return a},$1=function(){this.v=null;this.m="";this.H=this.D=this.F=this.K=this.C=this.j=this.h=this.J=null},a2=function(a){var b=a.ra;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return W1(X1(Y1(Z1((new $1).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},b2=function(a,
b,c){_ds.Zg.call(this,a,c);this.j=b},c2=function(a){this.h=a||null;this.next=a?null:{}},d2=function(a,b){var c=b.shift();_ds.kd(c,function(d){var e=a[d];e&&(0==b.length?e.h&&delete a[d]:e.next&&(d2(e.next,b.slice(0)),_ds.Yb(e.next)&&delete a[d]))})},g2=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),f=null,h=null;c=0;for(var k,l=0;k=e[l];l++){switch(k){case "shift":c|=1;continue;case "ctrl":c|=2;continue;
case "alt":c|=4;continue;case "meta":c|=8;continue}e=void 0;f=k;if(!e2){h={};for(e in f2)h[f2[e]]=_ds.nD(parseInt(e,10));e2=h}h=e2[f];f=k;break}b.push({key:f,keyCode:h,modifiers:c})}return b},h2=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},i2=function(a,b){if("string"===typeof b[a])a=_ds.Nb(g2(b[a]),function(e){return h2(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(h2("",c[d],c[d+1]))}return a},
j2=function(a,b){32==a.D&&32==b.h&&(0,b.j)();a.D=null},k2=function(a){return _ds.fJ&&a.m&&a.v},l2=function(a,b,c){var d=b.shift();_ds.kd(d,function(e){if((e=a[e])&&(0==b.length||e.h))throw Error("Keyboard shortcut conflicts with existing shortcut: "+e.h);});b.length?_ds.kd(d,function(e){e=e.toString();var f=new c2;e=e in a?a[e]:a[e]=f;l2(e.next,b.slice(0),c)}):_ds.kd(d,function(e){a[e]=new c2(c)})},m2=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},n2=function(a,b,c){a:{var d=
b.h;if(""!=b.C){var e=b.C;if("Control"==e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.J;var f="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,h=!f&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!f&&!h||a.L[d]||a.F?!0:h?!1:a.M&&(b.v||b.m||b.D)?!0:"INPUT"==e.tagName&&a.R[e.type]?13==d:"INPUT"==e.tagName||"BUTTON"==e.tagName?a.N?!0:32!=d:!1}if(d)if(!c&&k2(b))a.m=!1;else{c=_ds.nD(b.h);
d=h2(b.C,c,(b.H?1:0)|(b.m?2:0)|(b.v?4:0)|(b.D?8:0));e=m2(a.v,d);if(!e||1500<=Date.now()-a.C)a.v=a.j,a.C=Date.now();(e=m2(a.v,d))&&e.next&&(a.v=e.next,a.C=Date.now());e&&(e.next?(0,b.j)():(a.v=a.j,a.C=Date.now(),a.H&&(0,b.j)(),a.K&&(0,b.K)(),d=e.h,e=a.dispatchEvent(new b2("shortcut",d,b.F)),(e&=a.dispatchEvent(new b2("shortcut_"+d,d,b.F)))||(0,b.j)(),_ds.Kl&&(a.D=c)))}},o2=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=m2(b,d))&&(0==c.length&&d.h||o2(a,d.next,c.slice(0))))return!0}return!1},
r2=function(a){_ds.Fk.call(this);this.v=this.j={};this.C=0;this.L=U1(p2);this.R=U1(q2);this.H=!0;this.F=this.K=!1;this.M=!0;this.N=!1;this.D=null;this.h=a;_ds.mh(this.h,"keydown",this.Yj,void 0,this);_ds.mh(this.h,"synthetic-keydown",this.fk,void 0,this);_ds.fJ&&(_ds.mh(this.h,"keypress",this.hk,void 0,this),_ds.mh(this.h,"synthetic-keypress",this.jk,void 0,this));_ds.mh(this.h,"keyup",this.Zj,void 0,this);_ds.mh(this.h,"synthetic-keyup",this.gk,void 0,this)},s2=function(a,b){return _ds.yg(a,10,b)},
t2=function(a){return(0,_ds.T)('<div class="devsite-popout" id="'+_ds.X(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},u2=function(a){var b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.W(a);return(0,_ds.T)(b+a+"</button>")},v2=function(a,b,c){var d='<button type="submit" class="button button-white devsite-suggest-all-results">';b?(a="All results across "+_ds.W(c),d+=a):(a='All results for "'+
_ds.W(a)+'"',d+=a);return(0,_ds.T)(d+"</button>")},w2=function(a,b,c,d,e,f,h,k){a=(c?"":'<devsite-analytics-scope action="'+_ds.X(_ds.PC("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.X(_ds.PC(a))+'"><span class="devsite-suggestion-fragment">'+_ds.W(b)+"</span>"+(k?'<span class="devsite-suggestion-fragment">'+_ds.W(k)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.W(e)+"</span>":"")+(_ds.oC(f)&&!h?'<span class="devsite-suggestion-fragment">'+_ds.W(f)+"</span>":
"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.T)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},x2=function(a){var b=a.projectName,c=a.cl,d=a.query,e=a.Fl;a=a.Gf;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?u2(b):"")+v2(d,c,a)+"</div>":"")+"</div>");
return(0,_ds.T)(b)},y2=function(a){var b=a.Rq,c=a.er,d=a.vr,e=a.projectName,f=a.cl,h=a.query,k=a.Br,l=a.Fl;a=a.Gf;var m='<div class="devsite-suggest-wrapper '+(l?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">Suggested searches'+((f?'<span class="devsite-suggest-project">'+
_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var n=d.length,q=0;q<n;q++){var t=d[q];m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+w2(t.getPath(),t.getTitle(),_ds.xg(t,14),"Query Suggestion Click")+"</div>"}m+="</devsite-analytics-scope></div>"}m+=
0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">Pages'+((f?'<span class="devsite-suggest-project">'+_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');n=b.length;for(q=0;q<n;q++)t=
b[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+w2(t.getPath(),t.getTitle(),_ds.xg(t,14),"Page Suggestion Click",void 0,_ds.J(t,4),f)+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<k.length&&0<b.length+d.length?'<hr role="none">':"";if(0<k.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">Reference'+
((f?'<span class="devsite-suggest-project">'+_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');n=k.length;for(q=0;q<n;q++)t=k[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+w2(t.getPath(),t.getTitle(),_ds.xg(t,14),"Reference Suggestion Click",_ds.J(t,3),
_ds.J(t,4),f,_ds.H(t,10)[0])+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<c.length&&0<b.length+d.length+k.length?'<hr role="none">':"";if(0<c.length){m+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)k=c[d],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.X(d)+'" role="listitem" index=":'+_ds.X(d)+'">'+w2(k.getPath(),k.getTitle(),_ds.xg(k,14),"Product Suggestion Click")+"</div>";m+="</devsite-analytics-scope></div>"}m+="</div>"+(l?'<div class="devsite-suggest-footer">'+(f?u2(e):"")+v2(h,f,a)+"</div>":"")+"</div>";return(0,_ds.T)(m)},z2=function(){var a=_ds.N.call(this)||this;a.N=!1;a.H={};a.K="";a.F=null;a.j=new _ds.yl;a.h=null;
a.M=!1;return a},G2=function(a){a.h&&(a.j.listen(a.h,"suggest-service-search",function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}A2(a,b.detail.originalEvent,!!a.F)}}),a.j.listen(a.h,"suggest-service-suggestions-received",function(b){return void B2(a,b)}),a.j.listen(a.h,"suggest-service-focus",function(){C2(a,"cloud-track-search-focus",null);a.M=!0;D2(a,!0)}),a.j.listen(a.h,"suggest-service-blur",function(){D2(a,!1)}),a.j.listen(a.h,
"suggest-service-input",function(){!a.H["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.H["Text Entered Into Search Bar"]=!0);a.M&&(C2(a,"cloud-track-search-input",null),a.M=!1)}),a.j.listen(a.h,"suggest-service-navigate",function(b){return void E2(a,b)}),a.j.listen(document.body,"devsite-page-changed",function(){return a.H=
{}}),a.h.Jl("SLASH",191),a.j.listen(document.body,"mousedown",function(b){F2(a,b)}));a.m&&a.j.listen(a.m,"submit",function(b){A2(a,b)});a.D&&a.j.listen(a.D,"click",function(b){var c=b.target,d=c.closest(".devsite-result-item-link");d&&(D2(a,!1),d="suggestion: "+d.getAttribute("href"),C2(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&A2(a,b,!0)});a.R&&a.j.listen(a.R,"click",function(){return void D2(a,!0)});a.T&&a.j.listen(a.T,"click",function(){return void D2(a,
!1)})},A2=function(a,b,c){c=void 0===c?!1:c;var d,e;_ds.Va(function(f){if(1==f.j){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return f.G(0);a.H["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.H["Full Site Search"]=!0);C2(a,"cloud-track-search-submit",a.L?"contains: "+a.L:"no match");d=c&&a.F?_ds.dk(a.F):_ds.dk(a.m.getAttribute("action"));
e=new _ds.yj(d.href);_ds.Lj(e,"q",a.h.query);d.search=e.h.toString();return _ds.x(f,DevsiteApp.fetchPage(d.href),3)}D2(a,!1);_ds.y(f)})},F2=function(a,b){_ds.Pi(b.target,function(c){return c===a})||D2(a,!1)},E2=function(a,b){var c=b.detail;b=a.C.querySelector(".highlight");var d,e=Array.from(a.C.querySelectorAll(".devsite-result-item")),f=[],h=-1;if(b){var k=_ds.Pi(b,function(m){return m.classList.contains("devsite-suggest-section")});f=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.ui(b.parentNode.parentNode);
var l=_ds.vi(b.parentNode.parentNode);h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&!l)return;b&&(c=b.getAttribute("index"),l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.zb(Array.from(l.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.zb(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!l)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.zb(Array.from(k.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+
c+'"]'))||(d=_ds.zb(Array.from(l.querySelectorAll("[index]"))))));break;case 38:b?(d=e[h-1])||(d=_ds.zb(f)):d=_ds.zb(e);break;case 40:b?(d=e[h+1])||(d=f[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.J.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},C2=function(a,b,c){a.dispatchEvent(new CustomEvent(b,{detail:{type:"search",
name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},D2=function(a,b){if(a.N!==b){_ds.tD(a.h,b);if(a.N=b)a.setAttribute("search-active","");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.mi(a.C)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},B2=function(a,b){a.L=null;b=b.detail;var c=b.suggestions,d=b.query;if(a.h.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=
c.Lb();0<e.length&&(b=e.filter(function(t){return t.getTitle().includes(d)}),0<b.length&&(a.L=b[0].getTitle()));b=e.filter(function(t){return 2===t.yc()});c=e.filter(function(t){return 3===t.yc()});var f=e.filter(function(t){return 4===t.yc()}).slice(0,5),h=e.filter(function(t){return 1===t.yc()});e=b.length+f.length+h.length;for(var k=_ds.p(f),l=k.next();!l.done;l=k.next())l=l.value,l.setPath(_ds.dk((a.F||"/s/results")+"/?q="+l.getTitle()).toString());var m=d.split(H2);c.forEach(function(t){return s2(t,
_ds.H(t,10).filter(function(u){return m.some(function(v){return u.includes(v)})}))});k=a.getAttribute("project-name")||"";l=a.hasAttribute("project-scope");var n=a.hasAttribute("enable-search"),q=a.getAttribute("tenant-name")||"";b={Rq:b,projectName:k,cl:l,er:h,vr:f,query:d,Br:c,Fl:n,Gf:q};0===e?_ds.eD(a.C,x2,b):(_ds.eD(a.C,y2,b),I2(a,d));a.setAttribute("aria-expanded","true");a.C.removeAttribute("hidden")}else a.C.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},I2=function(a,b){b=
new RegExp("("+_ds.Td(b)+")","ig");a=_ds.p(a.C.querySelectorAll(".devsite-suggestion-fragment"));for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");d=_ds.hF(d);_ds.Jd(c,d)}},f2={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",
59:"semicolon",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",
121:"f10",122:"f11",123:"f12",186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",192:"`",219:"open-square-bracket",220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.g=$1.prototype;_ds.g.keyCode=function(a){this.v=a;return this};_ds.g.key=function(a){this.m=a;return this};_ds.g.shiftKey=function(a){this.J=a;return this};_ds.g.altKey=function(a){this.h=a;return this};_ds.g.ctrlKey=function(a){this.j=a;return this};_ds.g.metaKey=function(a){this.C=a;return this};
_ds.g.target=function(a){this.K=a;return this};_ds.ub(b2,_ds.Zg);var p2=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],q2="color date datetime datetime-local email month number password search tel text time url week".split(" "),e2;_ds.ub(r2,_ds.Fk);_ds.g=r2.prototype;_ds.g.m_=function(){return this.H};_ds.g.Cfa=function(a){this.K=a};_ds.g.n_=function(){return this.K};_ds.g.zfa=function(a){this.F=a};_ds.g.j_=function(){return this.F};_ds.g.Fja=function(a){this.M=a};_ds.g.L2=function(){return this.M};
_ds.g.Bfa=function(a){this.N=a};_ds.g.zl=_ds.ea(0);_ds.g.una=function(a){d2(this.j,i2(0,arguments))};_ds.g.Cba=function(a){return o2(this,this.j,i2(0,arguments))};_ds.g.fia=function(a){this.L=U1(a)};_ds.g.B1=function(){return _ds.Xb(this.L)};
_ds.g.va=function(){r2.Ea.va.call(this);this.j={};_ds.wh(this.h,"keydown",this.Yj,!1,this);_ds.wh(this.h,"synthetic-keydown",this.fk,!1,this);_ds.fJ&&(_ds.wh(this.h,"keypress",this.hk,!1,this),_ds.wh(this.h,"synthetic-keypress",this.jk,!1,this));_ds.wh(this.h,"keyup",this.Zj,!1,this);_ds.wh(this.h,"synthetic-keyup",this.gk,!1,this);this.h=null};_ds.g.eK=function(a){return"shortcut_"+a};_ds.g.Zj=function(a){a=a2(a);_ds.Kl&&j2(this,a);_ds.fJ&&!this.m&&k2(a)&&n2(this,a,!0)};
_ds.g.gk=function(a){a=a.j();_ds.Kl&&j2(this,a);_ds.fJ&&!this.m&&k2(a)&&n2(this,a,!0)};_ds.g.hk=function(a){a=a2(a);32<a.h&&k2(a)&&(this.m=!0)};_ds.g.jk=function(a){a=a.j();32<a.h&&k2(a)&&(this.m=!0)};_ds.g.Yj=function(a){n2(this,a2(a))};_ds.g.fk=function(a){n2(this,a.j())};
_ds.uD.prototype.Jl=T1(1,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.h&&this.h.dispose();a&&(this.h=new r2(document),this.h.H=!1,this.h.zl.apply(this.h,[a].concat(_ds.qa(c))),this.eventHandler.listen(this.h,"shortcut",function(f){var h=document;h.activeElement&&h.activeElement===h.body&&(f.preventDefault(),_ds.tD(e,!0))}))});r2.prototype.zl=T1(0,function(a,b){l2(this.j,i2(1,arguments),a)});var H2=/[ .()<>{}\[\]\/:,]+/,J2=0;_ds.r(z2,_ds.N);z2.prototype.disconnectedCallback=function(){_ds.El(this.j);this.h&&(this.h.dispose(),this.h=null)};z2.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.K=c||"";this.h&&(this.h.L=this.K);break;case "url-scoped":this.F=c;break;case "disabled":this.J&&(this.J.disabled=null!==c)}};
z2.prototype.connectedCallback=function(){if(this.m=this.querySelector("form")){this.J=this.m.querySelector(".devsite-search-query");this.R=this.m.querySelector(".devsite-search-button[search-open]");this.T=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++J2;this.J.setAttribute("aria-controls",a);this.D=_ds.hD(t2,{id:a});this.C=this.D.querySelector(".devsite-suggest-results-container");this.m.appendChild(this.D);this.hasAttribute("project-scope")&&
(this.K=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.F=this.getAttribute("url-scoped"));this.m&&this.J&&(this.h=new _ds.uD(this.m,this.J),this.h.j=!0,this.h.Ug=this.hasAttribute("enable-query-completion"),this.h.cf=!0,this.h.Tg=!0,this.h.Vg=!0,this.h.L=this.K,this.h.j=this.hasAttribute("enable-suggestions"));G2(this)}};_ds.ka.Object.defineProperties(z2,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});
z2.prototype.connectedCallback=z2.prototype.connectedCallback;z2.prototype.attributeChangedCallback=z2.prototype.attributeChangedCallback;z2.prototype.disconnectedCallback=z2.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",z2)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
