(function(_ds){var window=this;'use strict';var PP=function(){_ds.Os.apply(this,arguments);this.m=null},QP=function(a){return _ds.M(a,function c(){var d=this,e;return _ds.F(c,function(f){if(1==f.j)return _ds.x(f,_ds.Qs(d),2);if(3!=f.j)return d.m?f.return(d.m):_ds.x(f,d.Ra(),3);e=f.h;d.m=new _ds.vq(e);return f.return(d.m)})})},RP=function(a){var b=a.sb;a=_ds.T;var c=b[0].imageUrl,d=b[0].url,e=b[0].servePath,f=b[0].nextPlaylistUrl,h=b[0].redeemAnotherBtn,k=b[0].hideButtons,l=b[0].shareTitle,m=b[0].shareDescription;b=(0,_ds.T)('<div class="devsite-badger-award"><div class="devsite-badger-award-inner"><devsite-badge-awarded badge-name="'+
_ds.X(b[0].title)+'" badge-icon-url="'+_ds.X(_ds.PC(c))+'" badge-url="'+_ds.X(_ds.PC(d))+'"'+(e?' badge-path="'+_ds.X(e)+'"':"")+(l?' badge-share-title="'+_ds.X(l)+'"':"")+(m?' badge-share-description="'+_ds.X(m)+'"':"")+(f?' next-playlist-url="'+_ds.X(_ds.PC(f))+'"':"")+(h?" redeem-another":"")+(k?" hide-buttons":"")+" dismiss></devsite-badge-awarded></div></div>");return a(b)},TP=function(){var a=_ds.iF.call(this,["devsite-badge-awarded"])||this;a.eventHandler=new _ds.yl(a);a.h=new _ds.ID;a.Ga=
null;a.sb=[];a.j=new _ds.vl(function(){return void SP(a)},250);return a},UP=function(a){null===a||void 0===a?void 0:a.setAttribute("show","")},VP=function(a){return _ds.M(a,function c(){var d=this;return _ds.F(c,function(e){if(1==e.j){if(!d.Ga)return e.return();d.h.remove("temp_badge");d.Ga.removeAttribute("show");return _ds.x(e,_ds.rk(200),2)}if(3!=e.j)return _ds.qi(d.Ga),d.Ga=null,_ds.x(e,_ds.rk(250),3);d.j.xa();_ds.y(e)})})},SP=function(a){return _ds.M(a,function c(){var d=this,e,f,h,k;return _ds.F(c,
function(l){switch(l.j){case 1:e=d;if(d.Ga||0===d.sb.length||"error"===document.body.getAttribute("type")||WP.exec(document.location.pathname))return l.return();_ds.C(l,2);return _ds.x(l,window.customElements.whenDefined("devsite-badge-awarded"),4);case 4:_ds.D(l,3);break;case 2:_ds.E(l);case 3:f=d.sb.splice(0,1);h=_ds.hD(RP,{sb:f});if(!h)return l.return();d.eventHandler.listen(h,"click",function(m){(m=m.target)&&m.matches("button.dismiss")&&VP(e)});d.Ga=h;(k=h.querySelector("devsite-badge-awarded"))?
(_ds.Cl(d.eventHandler,k,"running",function(){UP(e.Ga)}),document.body.appendChild(d.Ga)):(document.body.appendChild(d.Ga),UP(d.Ga));_ds.y(l)}})})},XP=function(a){a.eventHandler.listen(document.body,"devsite-before-page-change",function(){return void VP(a)});a.eventHandler.listen(document.body,"devsite-award-granted",function(b){(b=b.ra)&&b.detail&&(a.sb.push(b.detail.award),a.j.xa())});a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-page-changed"],function(){a.pd();a:if(_ds.Mu(a.h)){var b=
a.h.get("temp_badge");if(b){var c=null;try{c=JSON.parse(b)}catch(e){a.h.remove("temp_badge");break a}if(c)if(3>c.displayCount){a.h.set("temp_badge",JSON.stringify(c));b=new URL(c.awardedBy,document.location.origin);var d=_ds.Wj();if(!c.awardedBy||b.origin===d.origin&&b.pathname===d.pathname)a.sb.push(c),a.j.xa()}else a.h.remove("temp_badge")}}})};_ds.r(PP,_ds.Os);_ds.g=PP.prototype;
_ds.g.lc=function(){return _ds.M(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.x(e,QP(c),2);d=e.h;return e.return(d.lc())})})};
_ds.g.jd=function(a){a=void 0===a?!1:a;return _ds.M(this,function c(){var d=this,e,f,h,k,l;return _ds.F(c,function(m){switch(m.j){case 1:return _ds.x(m,QP(d),2);case 2:return e=m.h,f=_ds.Xs(d,"getWalletId",a),h=_ds.Ys(d,f),h||(h=e.jd(a),_ds.$s(d,f,h)),k=null,_ds.C(m,3,4),_ds.x(m,h,6);case 6:k=m.h;case 4:_ds.Ea(m);_ds.Zs(d,f);_ds.Ga(m,5);break;case 3:throw l=_ds.E(m),l;case 5:return m.return(k)}})})};
_ds.g.Wd=function(){return _ds.M(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.x(e,QP(c),2);d=e.h;return e.return(d.Wd())})})};_ds.g.pd=function(){return _ds.M(this,function b(){var c=this,d,e,f,h;return _ds.F(b,function(k){switch(k.j){case 1:return _ds.x(k,QP(c),2);case 2:return d=k.h,e=_ds.Xs(c,"syncWallet"),f=_ds.Ys(c,e),f||(f=d.pd(),_ds.$s(c,e,f)),_ds.C(k,3,4),_ds.x(k,f,4);case 4:_ds.Ea(k);_ds.Zs(c,e);_ds.Ga(k,0);break;case 3:throw h=_ds.E(k),h;}})})};
_ds.g.Od=function(){return _ds.M(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.x(e,QP(c),2);d=e.h;d.Od();_ds.y(e)})})};var WP=/\/redeem.*|\/u[\/]?.*|\/settings[\/]?.*?/;_ds.r(TP,_ds.iF);TP.prototype.connectedCallback=function(){XP(this)};TP.prototype.disconnectedCallback=function(){_ds.El(this.eventHandler);VP(this)};
TP.prototype.pd=function(){return _ds.M(this,function b(){var c,d,e,f,h;return _ds.F(b,function(k){switch(k.j){case 1:return _ds.x(k,DevsiteApp.whenReady(),2);case 2:return _ds.x(k,window.customElements.whenDefined("devsite-user"),3);case 3:c=document.querySelector("devsite-user#devsite-user");if(!c)return k.return();d=!1;_ds.C(k,4);return _ds.x(k,c.isSignedIn(),6);case 6:d=k.h;_ds.D(k,5);break;case 4:_ds.E(k);case 5:if(!d)return k.return();e=new PP;return _ds.x(k,e.lc(),7);case 7:f=k.h;if(!f)return k.return();
h=new _ds.ht;_ds.C(k,8);return _ds.x(k,h.ea(),10);case 10:_ds.D(k,0);break;case 8:_ds.E(k),_ds.y(k)}})})};try{window.customElements.define("devsite-badger",TP)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBadger",a)};})(_ds_www);
