(function(_ds){var window=this;'use strict';var K2=function(){return(0,_ds.T)('<div class="devsite-select"></div>')},L2=function(a){var b=a.Ah,c=a.Cd;a='<label id="'+_ds.X(a.id)+'-label" style="display:none;"'+(c?' aria-label="'+_ds.X(c)+'"':"")+">";return(0,_ds.T)((b?a+"Select one or more options":a+"Select an option")+"</label>")},M2=function(a){var b=a.label;a=a.id;return(0,_ds.T)('<button type="button" class="devsite-select-toggle" id="'+_ds.X(a)+'-button" aria-haspopup="true" aria-labelledby="'+_ds.X(a)+"-label "+_ds.X(a)+
'-button" aria-controls="'+_ds.X(a)+'-popup"><span class="devsite-select-toggle-label">'+_ds.W(b)+"</span></button>")},N2=function(){return(0,_ds.T)('<span class="devsite-icon devsite-icon-arrow-drop-down devsite-select-toggle-icon" aria-hidden="true"></span>')},O2=function(a){var b=a.options,c=a.id;a=a.Ah;a='<ul class="devsite-select-list" id="'+_ds.X(c)+'-popup" tabindex="-1" role="listbox" scrollbars aria-labelledby="'+_ds.X(c)+'-button"'+(a?' aria-multiselectable="true"':"")+">";for(var d=b.length,
e=0;e<d;e++){var f=b[e];a+='<li role="option"';for(var h=_ds.BD(f.attributes),k=h.length,l=0;l<k;l++){var m=h[l];a+=" "+_ds.FC(m)+'="'+_ds.X(f.attributes.get(m))+'"'}a+=' id="'+_ds.X(c)+"-"+_ds.X(e)+'" class="devsite-select-item" data-index="'+_ds.X(e)+'"'+(f.defaultSelected?' data-selected aria-selected="true"':' aria-selected="false"')+' aria-label="'+_ds.X(f.Cd)+'">'+_ds.W(f.label)+"</li>"}return(0,_ds.T)(a+"</ul>")},P2=function(){var a=_ds.N.call(this)||this;a.m=null;a.H=null;a.D=new _ds.yl;a.J=
new _ds.yl;a.N=null;a.L=!1;a.C=!1;a.M="";a.h=null;a.F=null;a.T=null;a.j=null;a.K=null;a.R=new _ds.wl;return a},Q2=function(a){var b=a.querySelector(".kd-select");b&&(b.classList.remove("kd-select"),Array.from(b.classList).forEach(function(c){a.classList.add(c);b.classList.remove(c)}))},V2=function(a){a.j=a.querySelector("select");var b;(b=a.j.id)||(R2++,b="devsite-select-"+R2+Math.random().toString().substr(2));a.j&&(a.j.options.length&&(a.K=a.j.options),a.j.hasAttribute("multiple")&&(a.C=!0,a.classList.add("devsite-select--multiple")));
if(a.K){var c=_ds.hD(K2),d=a.j.options;d=d[a.j.selectedIndex]||d[0];a.M=a.hasAttribute("label")?a.getAttribute("label"):d.label;d={Cd:a.j.getAttribute("aria-label"),id:b,Ah:a.C};d=_ds.hD(L2,d);c.appendChild(d);a.F=_ds.hD(M2,{label:a.M,id:b});d=_ds.hD(N2);a.F.appendChild(d);c.appendChild(a.F);a.h=_ds.hD(O2,{options:Array.from(a.K).map(function(e){for(var f=e.defaultSelected,h=S2(e.label,e.defaultSelected),k=e.label,l=new Map,m=_ds.p(T2),n=m.next();!n.done;n=m.next())n=n.value,e.hasAttribute(n)&&l.set(n,
e.getAttribute(n));return{defaultSelected:f,Cd:h,label:k,attributes:l}}),id:b,Ah:a.C});c.appendChild(a.h);a.appendChild(c);a.T=a.querySelector(".devsite-select-toggle-label");a.j.hasAttribute("disabled")&&a.querySelector(".devsite-select-toggle").setAttribute("disabled","");U2(a)}a.L=!0},U2=function(a){a.D.listen(a.F,"click",function(b){clearTimeout(a.N);a.dispatchEvent(new CustomEvent("devsite-close-select",{bubbles:!0}));b.preventDefault();b.stopPropagation();a.hasAttribute("menu--open")?W2(a):
X2(a)});a.D.listen(a.h,"click",function(b){b.target.classList.contains("devsite-select-item")&&Y2(a,b.target)});a.D.listen(a.h,"focusout",function(){a.N=setTimeout(function(){return W2(a)},200)});a.D.listen(a.j,"change",function(){Z2(a,$2(a.querySelectorAll("option")))});a.D.listen(a.h,"keydown",function(b){var c=b.which||b.keyCode;switch(c){case 38:case 40:b.preventDefault();if(a.m){if(b=40===c?_ds.ui(a.m):_ds.vi(a.m))a.m.classList.remove("devsite-focused"),a.h.setAttribute("aria-activedescendant",
b.id),b.classList.add("devsite-focused"),a.m=b}else a3(a);a.m.scrollIntoView({block:"nearest"});break;case 13:case 32:b.preventDefault();Y2(a,a.m);break;case 9:case 27:W2(a)}});a.D.listen(a.F,"keydown",function(b){var c=b.which||b.keyCode;if(38===c||40===c)b.preventDefault(),a.hasAttribute("menu--open")||X2(a)})},X2=function(a){a.setAttribute("menu--open","");a.setAttribute("aria-expanded","true");a3(a);a.h.focus();"scrollIntoViewIfNeeded"in a.m&&a.m.scrollIntoViewIfNeeded()},W2=function(a){a.removeAttribute("menu--open");
a.removeAttribute("aria-expanded");a.J.listen(document.body,"click",a.H);a.J.listen(document.body,"devsite-close-select",a.H);a.m&&a.m.classList.remove("devsite-focused")},Y2=function(a,b){b&&(b3(a,parseInt(b.dataset.index,10)),a.C||(W2(a),a.F.focus()),a.j.dispatchEvent(new Event("change")))},a3=function(a){if(a.h){var b=Array.from(a.h.children).find(function(c){return c.hasAttribute("data-selected")});a.m=b?b:a.h.children[0];a.h.setAttribute("aria-activedescendant",a.m.id)}},c3=function(a){a.H=function(b){if("devsite-close-select"!==
b.type||b.target!==a)a.C&&"devsite-select-item"===b.target.className||W2(a)};a.h&&(a.J.listen(document.body,"click",a.H),a.J.listen(document.body,"devsite-close-select",a.H))},d3=function(a){if(a.h&&a.F){a.h.style.removeProperty("left");a.h.style.removeProperty("right");var b=a.h.getBoundingClientRect();0<b.x+b.width-_ds.xl(a.R).width?a.h.style.right="0":a.h.style.left="0"}},$2=function(a){return Array.from(a).reduce(function(b,c,d){c.selected&&b.push(d);return b},[])},b3=function(a,b){var c=a.querySelectorAll("option");
if(c&&c.length){if(!a.C)for(var d=_ds.p(c),e=d.next();!e.done;e=d.next())e.value.removeAttribute("selected");c[b]&&(b=c[b],a.C&&b.hasAttribute("selected")?b.removeAttribute("selected"):b.setAttribute("selected","true"));Z2(a,$2(c))}},Z2=function(a,b){var c=a.querySelectorAll(".devsite-select-item");Array.from(c).forEach(function(d,e){d=!1;b.includes(e)?(d=!0,c[e].setAttribute("data-selected",""),c[e].setAttribute("aria-selected","true"),a.h.setAttribute("aria-activedescendant",c[e].id)):(c[e].removeAttribute("data-selected"),
c[e].setAttribute("aria-selected","false"));c[e].setAttribute("aria-label",S2(c[e].textContent,d))});a.C||(a.T.textContent=a.j.options[b[0]].label);d3(a)},S2=function(a,b){return(void 0===b?0:b)?a+", selected":a},R2=0;var T2=["lang","title","value"];_ds.r(P2,_ds.N);
P2.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.Va(function(e){if(1==e.j){if("menu--open"!==a||b===c)return e.G(2);if(!d.hasAttribute("menu--open"))return d.removeAttribute("menu--show"),_ds.El(d.J),e.G(2);d3(d);d.removeAttribute("menu-position");if(d.h){var f=d.h.getBoundingClientRect(),h=_ds.xl(d.R).height,k=parseInt(_ds.Ml(d.h,"maxHeight"),10);d.setAttribute("menu-position",f.top+(d.h.scrollHeight>k?k:d.h.scrollHeight)<h?"below":"above")}c3(d);return _ds.x(e,0,4)}2!=
e.j&&d.setAttribute("menu--show","");"reset"===a&&b3(d,0);_ds.y(e)})};P2.prototype.connectedCallback=function(){this.L||(Q2(this),V2(this))};P2.prototype.disconnectedCallback=function(){_ds.El(this.J);_ds.El(this.D)};_ds.ka.Object.defineProperties(P2.prototype,{value:{configurable:!0,enumerable:!0,get:function(){return this.j.value},set:function(a){Y2(this,this.h.querySelector('.devsite-select-item[value="'+a+'"]'))}}});
_ds.ka.Object.defineProperties(P2,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["label","menu--open","reset"]}}});P2.prototype.disconnectedCallback=P2.prototype.disconnectedCallback;P2.prototype.connectedCallback=P2.prototype.connectedCallback;P2.prototype.attributeChangedCallback=P2.prototype.attributeChangedCallback;try{window.customElements.define("devsite-select",P2)}catch(a){console.warn("devsite.app.customElement.DevsiteSelect",a)};})(_ds_www);
