(function(_ds){var window=this;'use strict';var e3=function(a){return(void 0===a?"":a).toLowerCase().trim().replace(/\s+/g,"-").replace(/[!@#\$%\^&\*\(\)\{\}<>\?\\\/'"]+/g,"").trim()},f3=function(){var a=_ds.N.call(this,["devsite-tabs"])||this;a.j=new _ds.yl;a.m=!1;a.C=new _ds.ID;a.h=null;return a},g3=function(a,b){var c=a.getBoundingClientRect();a.dispatchEvent(new CustomEvent("devsite-sticky-freeze",{bubbles:!0}));var d=a.getAttribute("scope");Array.from(a.ownerDocument.querySelectorAll('devsite-selector[scope="'+d+'"]:not([active="'+
(b+'"])'))).forEach(function(h){h!==a&&h.setAttribute("tab-to-select",b)});a.setAttribute("active",b);var e=a.getBoundingClientRect();window.scrollTo(_ds.di(document).x,_ds.di(document).y+e.top-c.top);a.hasAttribute("no-pref")||a.C.set("pref_ds_"+d,b);var f;Array.from(a.children).forEach(function(h){!f&&h.matches("devsite-tabs")&&(f=h.querySelector('[tab="'+b+'"]'))});f&&f.id&&_ds.Xj("#"+f.id,!0);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},h3=function(a){a.h&&a.j.listen(a.h,
"click",function(b){if(!b.defaultPrevented){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));b=b.target;for(var c;!c&&b!==a;)"TAB"===b.tagName.toUpperCase()&&(c=b),b=b.parentNode;c&&g3(a,c.getAttribute("tab"))}})},i3=function(a){a.m=!0;var b=a.getAttribute("scope"),c=null,d=_ds.Wj().searchParams.get("tab");d&&(c=e3(d));c||a.hasAttribute("no-pref")||(c=a.C.get("pref_ds_"+b));var e=a.ownerDocument.createElement("devsite-tabs");e.setAttribute("role",
"tablist");a.hasAttribute("no-overflow")&&e.setAttribute("no-overflow","");a.h=e;Array.from(a.children).filter(function(h){return h.matches("section")}).forEach(function(h){var k=a.ownerDocument.createElement("tab"),l=a.ownerDocument.createElement("a");h.querySelector(".two-line-tab")&&k.setAttribute("two-line","");k.setAttribute("role","tab");k.setAttribute("aria-selected","false");var m=h.querySelector("h1,h2,h3,h4,h5,h6"),n="";if(m&&""!==m.textContent.trim()){n="";if(m.id)var q=m.id;var t=m.querySelector(".firebase-platform-label");
t&&(n=t.textContent.trim(),_ds.qi(t));t=m.textContent;var u=h.querySelector("[tab-label]");u&&(n=u.getAttribute("tab-label"));_ds.qi(m);n?(u=a.ownerDocument.createElement("span"),u.setAttribute("tab-label",n),u.textContent=t.trim(),l.appendChild(u),n=e3(t+" "+n)):(l.append.apply(l,_ds.qa(m.childNodes)),n=e3(t)||"tab");k.setAttribute("aria-controls","tabpanel-"+n);l.id="aria-tab-"+n;l.setAttribute("role","button");m.hasAttributes()&&Array.from(m.attributes).forEach(function(v){v.name.startsWith("track-")&&
l.setAttribute(v.name,v.value)})}else n="Error",m&&(n=m.getAttribute("data-text")||"Error"),l.textContent=n,n=e3(n);_ds.Ld(l,"#"+n);k.appendChild(l);e.querySelector('[tab="'+n+'"]')||(k.setAttribute("tab",n),q&&(k.id=q),e.appendChild(k));h.setAttribute("tab",n);h.setAttribute("role","tabpanel");h.setAttribute("aria-labelledby","aria-tab-"+n);h.setAttribute("tabindex","0");h.id="tabpanel-"+n});_ds.pi(a,e,0);b=_ds.Wj().hash.substring(1);var f=Array.from(a.children);d=e.querySelector('tab[id="'+b+'"]');
(f=f.find(function(h){return h.matches(".selected")}))&&f.classList.remove("selected");b&&d?a.setAttribute("active",d.getAttribute("tab")):c&&e.querySelector('[tab="'+c+'"]')?a.setAttribute("tab-to-select",c):f?a.setAttribute("active",f.getAttribute("tab")):a.hasAttribute("active")||a.setAttribute("active",e.querySelector("[tab]").getAttribute("tab"));a.setAttribute("ready","")},k3=function(a){Array.from(a.children).forEach(function(b){if(b.matches(".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample")){var c=
b.getAttribute("data-ds-scope");c&&a.setAttribute("scope",c);var d=".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample".split(/[,.]/).filter(function(e){return e.length});Array.from(b.classList).forEach(function(e){d.includes(e)||a.classList.add(e)});for(b.hasAttribute("no-overflow")&&a.setAttribute("no-overflow","");b.childNodes.length;)a.appendChild(b.childNodes[0]);_ds.qi(b)}});Array.from(a.children).forEach(function(b){b.matches(".kd-tabbed-horz,.kd-tabbed-vert")&&j3(a,b)})},j3=
function(a,b){Array.from(b.children).forEach(function(c){if(c.matches("article")){var d=a.ownerDocument.createElement("section");for(c.classList.contains("selected")&&d.classList.add("selected");c.childNodes.length;)d.appendChild(c.childNodes[0]);var e=d.querySelector("header");if(e){var f=a.ownerDocument.createElement("h3");e.childNodes.length&&f.append.apply(f,_ds.qa(e.childNodes));f.id=e.id;_ds.ri(f,e)}a.appendChild(d);_ds.qi(c)}});_ds.qi(b)};_ds.r(f3,_ds.N);
f3.prototype.connectedCallback=function(){k3(this);this.getAttribute("scope")||this.setAttribute("scope","auto");this.m||i3(this);h3(this)};f3.prototype.disconnectedCallback=function(){_ds.El(this.j)};
f3.prototype.attributeChangedCallback=function(a,b,c){var d=this,e=[],f=Array.from(this.children);f.forEach(function(k){k.matches('section[tab="'+c+'"]')?e.push(k):k.matches("devsite-tabs")&&(k=k.querySelector('tab[tab="'+c+'"]'))&&e.push(k)});"active"===a&&c&&(e.length?(f.forEach(function(k){if(k.matches("section[tab][active]"))k.removeAttribute("active");else if(k.matches("devsite-tabs")){var l=k.querySelector("tab[tab][active]");l&&(l.removeAttribute("active"),l.setAttribute("aria-selected","false"),
(k=k.querySelector("a[aria-selected=true]"))&&k.removeAttribute("aria-selected"))}}),e.forEach(function(k){k.setAttribute("active","");if(k.matches("tab")){k.setAttribute("aria-selected","true");var l=k.querySelector("a");l&&l.setAttribute("aria-selected","true")}Array.from(k.querySelectorAll("iframe[data-src]")).forEach(function(m){m.setAttribute("src",m.getAttribute("data-src"));m.removeAttribute("data-src")})})):this.setAttribute(a,b));if("tab-to-select"===a&&c){if(e.length)this.setAttribute("active",
c);else{var h=this.getAttribute("active");f.forEach(function(k){k.matches("devsite-tabs")&&(k=k.querySelector('tab[tab="'+h+'"]'))&&d.setAttribute("active",k.getAttribute("tab"))})}this.removeAttribute("tab-to-select")}};_ds.ka.Object.defineProperties(f3,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["active","tab-to-select"]}}});f3.prototype.attributeChangedCallback=f3.prototype.attributeChangedCallback;f3.prototype.disconnectedCallback=f3.prototype.disconnectedCallback;
f3.prototype.connectedCallback=f3.prototype.connectedCallback;try{window.customElements.define("devsite-selector",f3)}catch(a){console.warn("devsite.app.customElement.DevsiteSelector",a)};})(_ds_www);
