(function(_ds){var window=this;'use strict';var m4=function(a){var b=a.ai;a=a.Go;for(var c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">',d=a.length,e=0;e<d;e++){var f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.X(f.zj)+'" tabindex="0" track-type="navMenu" track-metadata-eventdetail="'+_ds.X(f.text)+'" track-name="'+_ds.X(b)+'" track-metadata-href="#'+_ds.X(f.zj)+'" track-metadata-position="nav - secondary" track-metadata-module_headline="'+_ds.X(b)+'">'+_ds.W(f.text)+
"</a></li>"}return(0,_ds.T)(c+"</ul></div>")},n4=function(a){var b=a.ai,c=a.href;a=a.text;return(0,_ds.T)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.X(_ds.PC(c))+'" track-type="navMenu" track-name="'+_ds.X(b)+'" track-metadata-eventdetail="'+_ds.X(a)+'" track-metadata-href="'+_ds.X(c)+'" track-metadata-position="nav - secondary" track-metadata-module_headline="'+_ds.X(b)+'">'+_ds.W(a)+"</a></div>")},F4=function(){var a=_ds.N.call(this)||this;a.M=20;a.eventHandler=new _ds.yl;a.j=new _ds.yl;
a.H=new _ds.vl(function(){o4(a)},a.M);a.K=null;a.C=null;a.J=!1;a.F=0;a.h=null;a.D=null;a.L=0;a.Ec=[];a.m=null;a.Da(a.v(p4),a.v(q4),a.v(r4),a.v(s4),a.v(t4),a.v(u4),a.v(v4),a.v(w4),a.v(x4),a.v(y4),a.v(z4),a.v(A4),a.v(B4),a.v(C4),a.v(D4),a.v(E4));return a},N4=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",function(){return a.H.xa()});a.eventHandler.listen(a,"click",function(e){if(!(e.shiftKey||e.ctrlKey||e.metaKey||e.altKey)){var f=e.target,h=a.gf(f);if(h)if(a.C&&a.C(e))e.preventDefault(),
e.stopPropagation();else if(h===a.h)G4(a,e);else if(H4(a),f.classList.contains("devsite-tabs-dropdown-toggle"))e.preventDefault(),e.stopPropagation(),h.hasAttribute("dropdown--open")?I4(a):J4(a,h);else{var k;"A"===f.tagName?k=f:k=_ds.Qi(f,"A");var l=h.querySelector(".devsite-tabs-dropdown");l&&l.contains(f)?k&&k.hasAttribute("href")||(e.preventDefault(),e.stopPropagation()):(a.Ri(h),k&&k&&"#"!==k.href||a.H.xa())}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b=
"onpointermove"in window?"pointerover":"mouseover",c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){b=_ds.p(d);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(e){var f,h=e.target,k=a.gf(h),l=null===k||void 0===k?void 0:k.querySelector(".devsite-tabs-dropdown");!l||(null===(f=a.h)||void 0===f?0:f.contains(h))||l.contains(h)||(e.preventDefault(),e.stopPropagation(),(null===k||void 0===k?0:k.hasAttribute("dropdown--open"))?
I4(a):K4(a,e))});a.eventHandler.listen(document.body,"click",function(e){a.m&&!a.m.contains(e.target)&&I4(a)})}else a.eventHandler.listen(a,b,function(e){return void L4(a,e)}),a.eventHandler.listen(a,c,function(){return void M4(a)})}b=[].concat(_ds.qa(a.querySelectorAll(".devsite-tabs-close-button")));b=_ds.p(b);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(){return I4(a)})},M4=function(a){return _ds.M(a,function c(){var d,e=this;return _ds.F(c,function(f){if(1==
f.j)return _ds.x(f,(0,_ds.Cn)(),2);d=f.h;if(d.isTouchEnabled())return f.return();I4(e,300);_ds.y(f)})})},L4=function(a,b){return _ds.M(a,function d(){var e,f=this;return _ds.F(d,function(h){if(1==h.j)return _ds.x(h,(0,_ds.Cn)(),2);e=h.h;if(e.isTouchEnabled())return h.return();K4(f,b);_ds.y(h)})})},K4=function(a,b){var c,d=b.target,e=a.gf(d);e&&(e===a.h||(null===(c=a.h)||void 0===c?0:c.contains(d))?G4(a,b):J4(a,e))},I4=function(a,b){b=void 0===b?0:b;_ds.El(a.j);window.clearTimeout(a.F);var c=a.querySelector("tab[dropdown--open]");
if(c){var d=c.querySelector(".devsite-tabs-dropdown");_ds.En(a,"dropdown-transition","",d);_ds.Cl(a.j,d,_ds.nI,function(){null===d||void 0===d?void 0:d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.En(a,"hidden","",d)});a.F=window.setTimeout(function(){c.removeAttribute("dropdown--open");O4(a,c)},b)}else a.removeAttribute("dropdown--open");H4(a)},J4=function(a,b){_ds.M(a,function d(){var e=this,f,h,k,l,m,n,q,t,u,v,w,B;return _ds.F(d,function(z){if(1==z.j){f=e;H4(e);
if(!b.hasAttribute("dropdown"))return I4(e),z.return();_ds.El(e.j);window.clearTimeout(e.F);return b.hasAttribute("dropdown--open")?z.return():_ds.x(z,(0,_ds.Cn)(),2)}h=z.h;h.isTouchEnabled()&&_ds.Cl(e.j,document.body,"click",function(A){f.contains(A.target)||I4(f)});k=e.querySelector("tab[dropdown--open]");l=b.querySelector(".devsite-tabs-dropdown");if(!l)return k&&(k.removeAttribute("dropdown--open"),O4(e,k)),z.return();l.removeAttribute("hidden");_ds.Il(l,"left","");m=_ds.ai(window||window);n=
Array.from(l.querySelectorAll(".devsite-tabs-dropdown-column"));!b.hasAttribute("dropdown-full")&&1<n.length&&(q=[],n.forEach(function(A){q.push(A.scrollWidth)}),t=Math.max.apply(null,q),u=t*n.length,u<m.width?n.forEach(function(A){_ds.Il(A,"width",t+"px")}):_ds.En(e,"dropdown-full","",b));v=l.getBoundingClientRect();b.hasAttribute("dropdown-full")?_ds.Il(l,"left","-"+v.left+"px"):(w=Math.min(v.left,v.left+v.width-m.width),0<w&&_ds.Il(l,"left","-"+w+"px"));k?(k.removeAttribute("dropdown--open"),O4(e,
k),B=k.querySelector(".devsite-tabs-dropdown"),null===B||void 0===B?void 0:B.removeAttribute("dropdown-transition"),_ds.En(e,"hidden","",B)):(_ds.En(e,"dropdown-transition","",l),_ds.Cl(e.j,l,_ds.nI,function(){return l.removeAttribute("dropdown-transition")}));window.requestAnimationFrame(function(){_ds.En(f,"dropdown--open","");_ds.En(f,"dropdown--open","",b);O4(f,b)});_ds.y(z)})})},G4=function(a,b){var c;_ds.M(a,function e(){var f=this,h,k,l;return _ds.F(e,function(m){switch(m.j){case 1:return h=
f,b.preventDefault(),b.stopPropagation(),document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs")),_ds.x(m,_ds.nk(),2);case 2:return f.hasAttribute("overflow-menu--open")?m.return():_ds.x(m,(0,_ds.Cn)(),3);case 3:return k=m.h,_ds.x(m,k.whenReady(),4);case 4:k.isTouchEnabled()&&(l=function(n){h.contains(n.target)||H4(h);_ds.Dl(h.j,document.body,["devsite-close-overflow-tabs","click"],l)},f.j.listen(document.body,["devsite-close-overflow-tabs","click"],l)),null===(c=f.D)||void 0===
c?void 0:c.removeAttribute("hidden"),_ds.En(f,"overflow-menu--open",""),_ds.y(m)}})})},H4=function(a){_ds.En(a,"hidden","",a.D);a.removeAttribute("overflow-menu--open")},o4=function(a){var b,c,d;_ds.En(a,"hidden","",a.h);if(!(a.Ec&&3>a.Ec.length)){var e=P4(a,a);if(0!==e){var f=(null===(b=a.Ec)||void 0===b?void 0:b.slice())||[],h=0,k;f.forEach(function(t){t.parentNode!==a.m&&(k?_ds.oi(t,k):_ds.pi(a.m,t,0));k=t;h+=P4(a,t)});if(!(h<=e)){var l=a.L;null===(c=a.h)||void 0===c?void 0:c.removeAttribute("hidden");
var m=a.querySelector("[active]");for(m&&(l+=P4(a,m));null===f||void 0===f?0:f.length;){var n=f.shift();if(n!==m){var q=P4(a,n||null);l+q<=e?l+=q:null===(d=a.D)||void 0===d?void 0:d.appendChild(n)}}}}}},Q4=function(a){var b;a.Ec=Array.from(a.querySelectorAll("tab"));var c=a.querySelector(".devsite-tabs-wrapper");c||(c=a.ownerDocument.createElement("div"),c.classList.add("devsite-tabs-wrapper"),a.appendChild(c),null===(b=a.Ec)||void 0===b?void 0:b.forEach(function(f){return null===c||void 0===c?void 0:
c.appendChild(f)}));a.m=c;a.appendChild(c);if(!a.hasAttribute("no-overflow")){var d=a.ownerDocument.createElement("tab");_ds.En(a,"overflow-tab","",d);var e=a.ownerDocument.createElement("a");_ds.Ld(e,"#");e.textContent="More";e.classList.add("devsite-icon");e.classList.add("devsite-icon-arrow-drop-down");d.appendChild(e);a.h=d;e=a.ownerDocument.createElement("div");e.classList.add("devsite-tabs-overflow-menu");_ds.En(a,"scrollbars","",e);_ds.En(a,"hidden","",e);a.D=e;d.appendChild(e);c.appendChild(d)}},
P4=function(a,b){if(!b)return 0;for(var c=[],d=b;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.En(a,"render-hidden","",d),d=d.parentElement;a=_ds.Tl(b).width;c=_ds.p(c);for(b=c.next();!b.done;b=c.next())b.value.removeAttribute("render-hidden");return a},O4=function(a,b){_ds.En(a,"aria-expanded",""+b.hasAttribute("dropdown--open"),b.querySelector(".devsite-tabs-dropdown-toggle"))},R4=function(a,b){return _ds.M(a,function d(){var e;return _ds.F(d,function(f){if(1==f.j)return _ds.x(f,(0,_ds.Cn)(),
2);e=f.h;return e.isTouchEnabled()||!b.hasAttribute("generated-tab-menu")?f.return(!1):f.return(!0)})})},U4=function(a){var b;null===(b=a.Ec)||void 0===b?void 0:b.forEach(function(c,d){return _ds.M(a,function f(){var h=this,k,l,m,n,q,t,u,v,w;return _ds.F(f,function(B){if(1==B.j)return k=h,_ds.x(B,R4(h,c),2);l=B.h;if(!l)return B.return();m=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column"));n=c.querySelector(".devsite-tabs-dropdown");q=c.querySelector("a");m.forEach(function(z,A){_ds.En(k,
"column-id","tab-"+d+"-column-"+A,z)});t=m.map(function(z){var A=z.querySelector(".devsite-nav-title")||z.querySelector(".devsite-nav-item-title");return{zj:z.getAttribute("column-id"),text:null===A||void 0===A?void 0:A.textContent}});q&&(u=_ds.hD(m4,{ai:q.textContent||"",Go:t}),n&&(v=c.querySelector(".devsite-tabs-dropdown-content")))&&(n.insertBefore(u,v),w=c.querySelector(".dropdown-tabbed-menu a"),S4(c),h.eventHandler.listen(u,"click",function(z){z.preventDefault();var A=c.querySelector(".dropdown-tabbed-menu-button");
z=z.target;A&&z.tagName&&"a"===z.tagName.toLowerCase()&&!A.contains(z)&&T4(k,c,(null===z||void 0===z?void 0:z.getAttribute("column-id"))||"")}),w&&T4(h,c,w.getAttribute("column-id")||""));_ds.y(B)})})})},T4=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(function(e){return e.removeAttribute("active")});d.forEach(function(e){return _ds.En(a,"hidden","",e)});b=b.find(function(e){return e.getAttribute("column-id")===
c});d=d.find(function(e){return e.getAttribute("column-id")===c});b&&d&&(_ds.En(a,"active","",b),d.removeAttribute("hidden"))},S4=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.hD(n4,{ai:c||"",href:b.getAttribute("href")||"",text:b.textContent||""}),null===a||void 0===a?void 0:
a.appendChild(c)))}};var p4=_ds.pa(["active"]),q4=_ds.pa(["aria-expanded"]),r4=_ds.pa(["aria-selected"]),s4=_ds.pa(["collapsed"]),t4=_ds.pa(["column-id"]),u4=_ds.pa(["connected"]),v4=_ds.pa(["dropdown"]),w4=_ds.pa(["dropdown-full"]),x4=_ds.pa(["dropdown--open"]),y4=_ds.pa(["dropdown-transition"]),z4=_ds.pa(["hidden"]),A4=_ds.pa(["no-overflow"]),B4=_ds.pa(["overflow-menu--open"]),C4=_ds.pa(["overflow-tab"]),D4=_ds.pa(["render-hidden"]),E4=_ds.pa(["scrollbars"]);_ds.r(F4,_ds.N);_ds.g=F4.prototype;
_ds.g.disconnectedCallback=function(){_ds.El(this.eventHandler);_ds.El(this.j)};_ds.g.connectedCallback=function(){this.J||(Q4(this),this.J=!0);_ds.En(this,"connected","");var a;this.hasAttribute("no-overflow")||(_ds.En(this,"collapsed","",this.h),this.L=P4(this,this.h),null===(a=this.h)||void 0===a?void 0:a.removeAttribute("collapsed"),N4(this),o4(this));U4(this)};_ds.g.gf=function(a){for(;a&&a!==this;){if("TAB"===a.tagName.toUpperCase())return a;a=a.parentElement}return null};
_ds.g.lN=function(a){this.C=a};_ds.g.Rea=function(){this.C=null};_ds.g.Ri=function(a){var b=this.K||this.querySelector("[active]");b&&(b.removeAttribute("active"),_ds.En(this,"aria-selected","false",b));_ds.En(this,"active","",a);_ds.En(this,"aria-selected","true",a);this.K=a};F4.prototype.connectedCallback=F4.prototype.connectedCallback;F4.prototype.disconnectedCallback=F4.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",F4)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
