(function(_ds){var window=this;'use strict';var UQ=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.ib(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},VQ=function(){var a=new _ds.KE;UQ(a.M,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},WQ=function(){var a=VQ();_ds.kd(["devsite-var"],function(b){this.L.push(b)},a);return a},XQ=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.sC("Action buttons");return(0,_ds.T)(a+'"></div>')},YQ=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},ZQ=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},$Q=function(a){var b=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.X(a.Lo)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.X(b)+'" data-title="'+_ds.X(b)+'"></button>')},aR=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},bR=function(){var a=_ds.N.call(this,["devsite-snackbar"])||this;a.h=null;a.m=null;a.K="";a.D=null;a.j=new _ds.yl;a.L=!1;a.C=null;a.F=null;a.M=new _ds.Fl;a.N=new _ds.OE(_ds.UE(WQ()));a.J=null;a.H=new _ds.ID;return a},cR=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
c=_ds.fF(a.N,c);_ds.Jd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},dR=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.K=b?"Copy code sample: "+b:"Copy code sample"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},eR=function(a){var b,c;return _ds.Va(function(d){if(1==d.j){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.QG(document.body,b);if(!a.J)return d.G(0);c=new _ds.Fl;a.m.setAttribute("aria-label","Code sample copied to clipboard");_ds.Cl(a.j,a.J,_ds.nI,function(){c.resolve()});return _ds.x(d,c.promise,3)}_ds.Cl(a.j,a.J,_ds.nI,function(){a.m.setAttribute("aria-label",a.K)});_ds.y(d)})},fR=function(a){a.D&&
a.j.listen(a.D,"click",function(){return void a.setAttribute("dark-code","")});a.F&&a.j.listen(a.F,"click",function(){return void a.removeAttribute("dark-code")});a.m&&a.j.listen(a.m,"click",function(){return void eR(a)});a.C&&a.j.listen(a.C,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.dH(c,b):_ds.cH([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(da){return da.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;")}function b(da,U,fa){switch(da.nodeType){case 1:var ia=da.tagName.toLowerCase();U.push("<",ia);var va=da.attributes,Sa=va.length;if(Sa){if(fa){for(var bb=[],ra=Sa;0<=--ra;)bb[ra]=va[ra];bb.sort(function(Ma,db){return Ma.name<db.name?-1:Ma.name===db.name?0:1});va=bb}for(ra=0;ra<Sa;++ra)bb=va[ra],bb.specified&&U.push(" ",bb.name.toLowerCase(),'="',bb.value.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(w,
"&quot;"),'"')}U.push(">");for(va=da.firstChild;va;va=va.nextSibling)b(va,U,fa);!da.firstChild&&/^(?:br|link|img)$/.test(ia)||U.push("</",ia,">");break;case 3:case 4:U.push(a(da.nodeValue))}}function c(da){function U(xa){if("\\"!==xa.charAt(0))return xa.charCodeAt(0);switch(xa.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(xa.substring(2),16)||xa.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(xa.substring(1),
8);default:return xa.charCodeAt(1)}}function fa(xa){if(32>xa)return(16>xa?"\\x0":"\\x")+xa.toString(16);xa=String.fromCharCode(xa);if("\\"===xa||"-"===xa||"["===xa||"]"===xa)xa="\\"+xa;return xa}function ia(xa){var Ha=xa.substring(1,xa.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);xa=[];for(var Aa=[],kb="^"===Ha[0],La=kb?1:0,ab=Ha.length;La<ab;++La){var Ta=Ha[La];switch(Ta){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":xa.push(Ta);
continue}Ta=U(Ta);if(La+2<ab&&"-"===Ha[La+1]){var Ca=U(Ha[La+2]);La+=2}else Ca=Ta;Aa.push([Ta,Ca]);65>Ca||122<Ta||(65>Ca||90<Ta||Aa.push([Math.max(65,Ta)|32,Math.min(Ca,90)|32]),97>Ca||122<Ta||Aa.push([Math.max(97,Ta)&-33,Math.min(Ca,122)&-33]))}Aa.sort(function(zc,Ac){return zc[0]-Ac[0]||Ac[1]-zc[1]});Ha=[];Ta=[NaN,NaN];for(La=0;La<Aa.length;++La)ab=Aa[La],ab[0]<=Ta[1]+1?Ta[1]=Math.max(Ta[1],ab[1]):Ha.push(Ta=ab);Aa=["["];kb&&Aa.push("^");Aa.push.apply(Aa,xa);for(La=0;La<Ha.length;++La)ab=Ha[La],
Aa.push(fa(ab[0])),ab[1]>ab[0]&&(ab[1]+1>ab[0]&&Aa.push("-"),Aa.push(fa(ab[1])));Aa.push("]");return Aa.join("")}function va(xa){for(var Ha=xa.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),Aa=Ha.length,kb=[],La=0,ab=0;La<Aa;++La){var Ta=Ha[La];"("===Ta?++ab:"\\"===Ta.charAt(0)&&(Ta=+Ta.substring(1))&&Ta<=ab&&(kb[Ta]=-1)}for(La=1;La<kb.length;++La)-1===kb[La]&&(kb[La]=++Sa);for(ab=La=0;La<Aa;++La)Ta=
Ha[La],"("===Ta?(++ab,void 0===kb[ab]&&(Ha[La]="(?:")):"\\"===Ta.charAt(0)&&(Ta=+Ta.substring(1))&&Ta<=ab&&(Ha[La]="\\"+kb[ab]);for(ab=La=0;La<Aa;++La)"^"===Ha[La]&&"^"!==Ha[La+1]&&(Ha[La]="");if(xa.ignoreCase&&bb)for(La=0;La<Aa;++La)Ta=Ha[La],xa=Ta.charAt(0),2<=Ta.length&&"["===xa?Ha[La]=ia(Ta):"\\"!==xa&&(Ha[La]=Ta.replace(/[a-zA-Z]/g,function(Ca){Ca=Ca.charCodeAt(0);return"["+String.fromCharCode(Ca&-33,Ca|32)+"]"}));return Ha.join("")}for(var Sa=0,bb=!1,ra=!1,Ma=0,db=da.length;Ma<db;++Ma){var aa=
da[Ma];if(aa.ignoreCase)ra=!0;else if(/[a-z]/i.test(aa.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){bb=!0;ra=!1;break}}var $a=[];Ma=0;for(db=da.length;Ma<db;++Ma){aa=da[Ma];if(aa.global||aa.multiline)throw Error(""+aa);$a.push("(?:"+va(aa)+")")}return new RegExp($a.join("|"),ra?"gi":"g")}function d(da){var U=0;return function(fa){for(var ia=null,va=0,Sa=0,bb=fa.length;Sa<bb;++Sa)switch(fa.charAt(Sa)){case "\t":ia||(ia=[]);ia.push(fa.substring(va,Sa));va=da-U%da;for(U+=va;0<=va;va-=
16)ia.push("                ".substring(0,va));va=Sa+1;break;case "\n":U=0;break;default:++U}if(!ia)return fa;ia.push(fa.substring(va));return ia.join("")}}function e(da,U,fa,ia){U&&(da={source:U,sj:da},fa(da),ia.push.apply(ia,da.Ij))}function f(da,U){function fa(bb){for(var ra=bb.sj,Ma=[ra,"pln"],db=0,aa=bb.source.match(va)||[],$a={},xa=0,Ha=aa.length;xa<Ha;++xa){var Aa=aa[xa],kb=$a[Aa],La=void 0;if("string"===typeof kb)var ab=!1;else{var Ta=ia[Aa.charAt(0)];if(Ta)La=Aa.match(Ta[1]),kb=Ta[0];else{for(ab=
0;ab<Sa;++ab)if(Ta=U[ab],La=Aa.match(Ta[1])){kb=Ta[0];break}La||(kb="pln")}!(ab=5<=kb.length&&"lang-"===kb.substring(0,5))||La&&"string"===typeof La[1]||(ab=!1,kb="src");ab||($a[Aa]=kb)}Ta=db;db+=Aa.length;if(ab){ab=La[1];var Ca=Aa.indexOf(ab),zc=Ca+ab.length;La[2]&&(zc=Aa.length-La[2].length,Ca=zc-ab.length);kb=kb.substring(5);e(ra+Ta,Aa.substring(0,Ca),fa,Ma);e(ra+Ta+Ca,ab,m(kb,ab),Ma);e(ra+Ta+zc,Aa.substring(zc),fa,Ma)}else Ma.push(ra+Ta,kb)}bb.Ij=Ma}var ia={},va;(function(){for(var bb=da.concat(U),
ra=[],Ma={},db=0,aa=bb.length;db<aa;++db){var $a=bb[db],xa=$a[3];if(xa)for(var Ha=xa.length;0<=--Ha;)ia[xa.charAt(Ha)]=$a;$a=$a[1];xa=""+$a;Ma.hasOwnProperty(xa)||(ra.push($a),Ma[xa]=null)}ra.push(/[\0-\uffff]/);va=c(ra)})();var Sa=U.length;return fa}function h(da){var U=[],fa=[];da.tripleQuotedStrings?U.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):da.multiLineStrings?
U.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):U.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);da.verbatimStrings&&fa.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var ia=da.hashComments;ia&&(da.cStyleComments?(1<ia?U.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):U.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),fa.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):U.push(["com",/^#[^\r\n]*/,null,"#"]));da.cStyleComments&&(fa.push(["com",/^\/\/[^\r\n]*/,null]),fa.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));da.regexLiterals&&fa.push(["lang-regex",new RegExp("^"+q+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);da=da.keywords.replace(/^\s+|\s+$/g,"");da.length&&fa.push(["kwd",new RegExp("^(?:"+da.replace(/\s+/g,
"|")+")\\b"),null]);U.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);fa.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(U,fa)}function k(da){function U(He){if(He>Ma){db&&db!==aa&&(ra.push("</span>"),db=null);!db&&aa&&(db=aa,ra.push('<span class="',db,'">'));var kf=a(Ha(fa.substring(Ma,
He))).replace(Ta?kb:Aa,"$1&#160;");Ta=ab.test(kf);ra.push(kf.replace(La,ag));Ma=He}}var fa=da.source,ia=da.kp,va=da.Ij,Sa=da.Ik,bb=da.Ol,ra=[],Ma=0,db=null,aa=null,$a=0,xa=0,Ha=d(window.PR_TAB_WIDTH),Aa=/([\r\n ]) /g,kb=/(^| ) /gm,La=/\r\n?|\n/g,ab=/[ \r\n]$/,Ta=!0,Ca=window._pr_isIE6();bb=Ca?bb&&"PRE"===bb.tagName?6===Ca?"&#160;\r\n":7===Ca?"&#160;<br />\r":8===Ca?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Sa){var zc=[];for(Ca=0;10>Ca;++Ca)zc[Ca]=bb+'</li><li class="L'+Ca+'">';var Ac="number"===
typeof Sa?Sa-1:0;ra.push('<ol class="linenums"><li class="L',Ac%10,'"');Ac&&ra.push(' value="',Ac+1,'"');ra.push(">");var ag=function(){var He=zc[++Ac%10];return db?"</span>"+He+'<span class="'+db+'">':He}}else ag=bb;for(;;)if($a<ia.length&&(xa<va.length?ia[$a]<=va[xa]:1))U(ia[$a]),db&&(ra.push("</span>"),db=null),ra.push(ia[$a+1]),$a+=2;else if(xa<va.length)U(va[xa]),aa=va[xa+1],xa+=2;else break;U(fa.length);db&&ra.push("</span>");Sa&&ra.push("</li></ol>");da.Gh=ra.join("")}function l(da,U){for(var fa=
U.length;0<=--fa;){var ia=U[fa];Ra.hasOwnProperty(ia)?"console"in window&&console.warn("cannot override language handler %s",ia):Ra[ia]=da}}function m(da,U){da&&Ra.hasOwnProperty(da)||(da=/^\s*</.test(U)?"default-markup":"default-code");return Ra[da]}function n(da){var U=da.Nl,fa=da.xk;da.Gh=U;try{var ia=U.match(ba);U=[];var va=0,Sa=[];if(ia)for(var bb=0,ra=ia.length;bb<ra;++bb){var Ma=ia[bb];if(1<Ma.length&&"<"===Ma.charAt(0)){if(!Z.test(Ma))if(la.test(Ma))U.push(Ma.substring(9,Ma.length-3)),va+=
Ma.length-12;else if(wa.test(Ma))U.push("\n"),++va;else if(0<=Ma.indexOf("nocode")&&Ma.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var db=Ma.match(Fa)[2],aa=1;var $a=bb+1;a:for(;$a<ra;++$a){var xa=ia[$a].match(Fa);if(xa&&xa[2]===db)if("/"===xa[1]){if(0===--aa)break a}else++aa}$a<ra?(Sa.push(va,ia.slice(bb,$a+1).join("")),bb=$a):Sa.push(va,Ma)}else Sa.push(va,Ma)}else{aa=Ma;var Ha=aa.indexOf("&");if(0>Ha)var Aa=aa;else{for(--Ha;0<=
(Ha=aa.indexOf("&#",Ha+1));){var kb=aa.indexOf(";",Ha);if(0<=kb){var La=aa.substring(Ha+3,kb),ab=10;La&&"x"===La.charAt(0)&&(La=La.substring(1),ab=16);var Ta=parseInt(La,ab);isNaN(Ta)||(aa=aa.substring(0,Ha)+String.fromCharCode(Ta)+aa.substring(kb+1))}}Aa=aa.replace(B,"<").replace(z,">").replace(A,"'").replace(Q,'"').replace(Y," ").replace(P,"&")}U.push(Aa);va+=Aa.length}}var Ca=U.join("");da.source=Ca;da.sj=0;da.kp=Sa;m(fa,Ca)(da);k(da)}catch(zc){"console"in window&&console.log(zc&&zc.stack?zc.stack:
zc)}}var q=function(){for(var da="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),U="(?:^^|[+-]",fa=0;fa<da.length;++fa)U+="|"+da[fa].replace(/([^=<>:&a-z])/g,"\\$1");return U+")\\s*"}(),t=/&/g,u=/</g,v=/>/g,w=/"/g,B=/&lt;/g,z=/&gt;/g,A=/&apos;/g,Q=/&quot;/g,P=/&amp;/g,Y=/&nbsp;/g,V=/[\r\n]/g,S=null,ba=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,
Z=/^\x3c!--/,la=/^<!\[CDATA\[/,wa=/^<br\b/i,Fa=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,za=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ra={};l(za,["default-code"]);l(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));l(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);l(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));l(h({keywords:"null true false"}),["json"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);l(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);l(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);l(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);l(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);l(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);l(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(da,U,fa){da={Nl:da,xk:U,Ik:fa};n(da);return da.Gh};window.prettyPrint=function(da){function U(){for(var aa=
window.PR_SHOULD_USE_CONTINUATION?ra.now()+250:Infinity;Ma<ia.length&&ra.now()<aa;Ma++){var $a=ia[Ma];if($a.className&&0<=$a.className.indexOf("prettyprint")){var xa=$a.className.match(/\blang-(\w+)\b/);xa&&(xa=xa[1]);for(var Ha=!1,Aa=$a.parentNode;Aa;Aa=Aa.parentNode)if(("pre"===Aa.tagName||"code"===Aa.tagName||"xmp"===Aa.tagName)&&Aa.className&&0<=Aa.className.indexOf("prettyprint")){Ha=!0;break}if(!Ha){Aa=$a;null===S&&(Ha=document.createElement("PRE"),Ha.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
S=!/</.test(Ha.innerHTML));if(S)if(Ha=Aa.innerHTML,"XMP"===Aa.tagName)Ha=a(Ha);else{if("PRE"!==Aa.tagName&&V.test(Ha)){var kb="";Aa.currentStyle?kb=Aa.currentStyle.whiteSpace:window.getComputedStyle&&(kb=window.getComputedStyle(Aa,null).whiteSpace);Aa=!kb||"pre"===kb}else Aa=!0;Aa||(Ha=Ha.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{Ha=[];for(Aa=Aa.firstChild;Aa;Aa=Aa.nextSibling)b(Aa,Ha);Ha=Ha.join("")}Ha=Ha.replace(/(?:\r\n?|\n)$/,"");Aa=$a.className.match(/\blinenums\b(?::(\d+))?/);
db={Nl:Ha,xk:xa,Ol:$a,Ik:Aa?Aa[1]&&Aa[1].length?+Aa[1]:!0:!1};n(db);if($a=db.Gh)if(xa=db.Ol,"XMP"===xa.tagName){Ha=document.createElement("PRE");for(Aa=0;Aa<xa.attributes.length;++Aa)kb=xa.attributes[Aa],kb.specified&&("class"===kb.name.toLowerCase()?Ha.className=kb.value:Ha.setAttribute(kb.name,kb.value));Ha.innerHTML=$a;xa.parentNode.replaceChild(Ha,xa)}else xa.innerHTML=$a}}}Ma<ia.length?setTimeout(U,250):da&&da()}for(var fa=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],ia=[],va=0;va<fa.length;++va)for(var Sa=0,bb=fa[va].length;Sa<bb;++Sa)ia.push(fa[va][Sa]);fa=null;var ra=Date;ra.now||(ra={now:function(){return(new Date).getTime()}});var Ma=0,db;U()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:l,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.r(bR,_ds.N);bR.prototype.whenReady=function(){return this.M.promise};
bR.prototype.connectedCallback=function(){var a=this,b;return _ds.Va(function(c){switch(c.j){case 1:return _ds.x(c,DevsiteApp.whenReady(),2);case 2:return a.L||(dR(a),cR(a),a.L=!0),a.H.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.M.resolve(),_ds.C(c,3),_ds.x(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.D(c,4);break;case 3:if(b=_ds.E(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.h=
d;else{a.h=_ds.hD(XQ);a.hasAttribute("scope")&&(a.C=_ds.hD(aR,{label:"Open code sample in JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.C.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.C));a.D=_ds.hD(YQ,{label:"Dark code theme"});a.h.appendChild(a.D);a.F=_ds.hD(ZQ,{label:"Light code theme"});a.h.appendChild(a.F);if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var e="Click To Copy";
d&&(e+=": "+d);a.m=_ds.hD($Q,{label:a.K,Lo:e});a.h.appendChild(a.m)}a.prepend(a.h)}fR(a);a.J=document.querySelector("devsite-snackbar");_ds.y(c)}})};bR.prototype.disconnectedCallback=function(){var a=this;return _ds.Va(function(b){if(1==b.j)return _ds.x(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.El(a.j);_ds.y(b)})};
bR.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.Va(function(e){if(1==e.j){if("dark-code"!==a||b===c)return e.G(0);if(d.hasAttribute("dark-code"))return d.H.set("pref_dark-code","1"),_ds.x(e,_ds.nk(),6);d.H.remove("pref_dark-code");return _ds.x(e,_ds.nk(),5)}if(6!=e.j)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(f){f.removeAttribute("dark-code")}),e.G(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(f){return f!==
d}).forEach(function(f){f.setAttribute("dark-code","")});_ds.y(e)})};_ds.ka.Object.defineProperties(bR,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});bR.prototype.attributeChangedCallback=bR.prototype.attributeChangedCallback;bR.prototype.disconnectedCallback=bR.prototype.disconnectedCallback;bR.prototype.connectedCallback=bR.prototype.connectedCallback;bR.prototype.whenReady=bR.prototype.whenReady;try{window.customElements.define("devsite-code",bR)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
